CREATE TABLE acidentes_fluminense (
    n_da_ocorrencia VARCHAR(50) PRIMARY KEY,
    data_acidente DATE,
    horario TIME,
    tipo_de_ocorrencia VARCHAR(100),
    km FLOAT,
    trecho VARCHAR(100),
    sentido VARCHAR(50),
    tipo_de_acidente VARCHAR(100),
    automovel INTEGER,
    bicicleta INTEGER,
    caminhao INTEGER,
    moto INTEGER,
    onibus INTEGER,
    outros INTEGER,
    tracao_animal INTEGER,
    transporte_de_cargas_especiais INTEGER,
    trator_maquinas INTEGER,
    utilitarios INTEGER,
    ilesos INTEGER,
    levemente_feridos INTEGER,
    moderadamente_feridos INTEGER,
    gravemente_feridos INTEGER,
    mortos INTEGER
);